In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import  joblib

# Data nilai siswa
nilai_siswa = np.array([55, 43, 98, 76, 65, 77, 65, 90])

# Buat label: 1 jika lulus (nilai >= 70), 0 jika tidak
y = (nilai_siswa >= 70).astype(int)

# Feature engineering sederhana:
# 1. Fitur asli (nilai_siswa)
# 2. Fitur biner apakah nilai >= 85 (nilai A)
is_A = (nilai_siswa >= 85).astype(int)

# 3. Deviasi nilai terhadap rata-rata
mean_nilai = nilai_siswa.mean()
deviation = nilai_siswa - mean_nilai

# Gabungkan fitur jadi matriks fitur (shape: n_samples x n_features)
X = np.column_stack((nilai_siswa, is_A, deviation))

# Standarisasi fitur agar nilai fitur seimbang dan model lebih stabil
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data train-test
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42
)

# Buat dan latih model Logistic Regression
model = LogisticRegression()
model.fit(X_train, y_train)

# Prediksi data test
y_pred = model.predict(X_test)

print("Data training (scaled features):\n", X_train)
print("Label training:", y_train)
print("Prediksi test:", y_pred)
print("Label asli test:", y_test)
print("Akurasi:", accuracy_score(y_test, y_pred))

# Simpan scaler dan model ke file
joblib.dump(scaler, './model/scaler.save')
joblib.dump(model, './model/logistic_model.save')

print("Model dan scaler sudah disimpan.")


Data training (scaled features):
 [[-0.95877    -0.57735027 -0.95877   ]
 [ 1.12228116  1.73205081  1.12228116]
 [ 1.59794999  1.73205081  1.59794999]
 [-0.36418395 -0.57735027 -0.36418395]
 [ 0.2898607  -0.57735027  0.2898607 ]
 [-0.36418395 -0.57735027 -0.36418395]]
Label training: [0 1 1 0 1 0]
Prediksi test: [0 1]
Label asli test: [0 1]
Akurasi: 1.0
Model dan scaler sudah disimpan.


: 

In [ ]:
from xanfispip  import Data, GdAnfisClassifier
from sklearn.datasets import load_breast_cancer

X, y = load_breast_cancer(return_X_y=True)
data = Data(X, y)
data.split_train_test(test_size=0.2, random_state=2, inplace=True)

model = GdAnfisClassifier(
    num_rules=20, mf_class="Trapezoidal", epochs=100, batch_size=16,
    optim="Adam", optim_params={"lr": 0.01}, early_stopping=True, n_patience=10,
    verbose=True
)
model.fit(X=data.X_train, y=data.y_train)
y_pred = model.predict(data.X_test)
print(model.evaluate(y_true=data.y_test, y_pred=y_pred, list_metrics=["F1S", "PS"]))

ModuleNotFoundError: No module named 'xanfis'